/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:a4d426fa-fee0-4a83-a47e-e530fbee6b31",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_D2sHqzj6y",
    "aws_user_pools_web_client_id": "mi9i88n3ig9c5et6reft27g2n",
    "oauth": {},
    "aws_user_files_s3_bucket": "vuepwasample7f1f7871e8c54239b175fdc211a1a1a8160048-dev",
    "aws_user_files_s3_bucket_region": "ap-northeast-1"
};


export default awsmobile;
